version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 2
  ignore:
  - dependency-name: gatsby-transformer-sharp
    versions:
    - 2.11.0
    - 2.12.0
    - 2.12.1
  - dependency-name: gatsby-plugin-feed
    versions:
    - 2.12.0
    - 2.13.0
  - dependency-name: gatsby-plugin-react-helmet
    versions:
    - 3.10.0
    - 3.9.0
  - dependency-name: gatsby-remark-copy-linked-files
    versions:
    - 2.10.0
    - 2.9.0
  - dependency-name: gatsby-plugin-google-analytics
    versions:
    - 2.10.0
